spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/diziman}
spring.datasource.username=${DATABASE_USERNAME:postgres}
spring.datasource.password=${DATABASE_PASSWORD:1254}
spring.jpa.hibernate.ddl-auto=update
server.port=${PORT:8080}
