spring.datasource.url=jdbc:postgresql://${PGHOST:localhost}:${PGPORT:5432}/${PGDATABASE:diziman}
spring.datasource.username=${PGUSER:postgres}
spring.datasource.password=${PGPASSWORD:1254}
spring.jpa.hibernate.ddl-auto=update
server.port=${PORT:8080}

# CO